- csc-sponsor-ssapp/code/modals/orderCreatedModal.html
I have removed the hard coded Order ID. Pleas review the code changes.
> change the order modal page

- csc-services/controllers/impl/SingleOrderControllerImpl.js
> Pending action corrected

- csc-site-ssapp/code/pages/order.html
I have removed the attachment section and review button for site. This belongs to issue-85.
> removed the attachment section and review button for site

- csc-site-ssapp/code/modals/historyModal.html
- csc-site-ssapp/code/pages/notifications.html
I have refactored the notification page and also the history modal for SITE.
> norification page modifed for SITE

- csc-cmo-ssapp/code/modals/orderCreatedModal.html
I have modified the order modal for CMO
> order modal modifed for CMO

- csc-services/controllers/impl/SingleOrderControllerImpl.js
- csc-services/index.js
- csc-services/services/ShipmentsService.js
CMO - Prepare Shipment button click action implemented. Checked rest of the Order creation till approval functionalities. It is working as usual.
> CMO - Prepare Shipment button click action implemented

- csc-cmo-ssapp/code/modals/editShipment.html
- csc-cmo-ssapp/code/pages/notifications.html
- csc-cmo-ssapp/code/scripts/controllers/EditShipmentController.js
- csc-cmo-ssapp/code/templates/shipment/table-template-shipment.html
- csc-services/controllers/impl/DashboardControllerImpl.js
- csc-services/controllers/impl/ShipmentsControllerImpl.js
- csc-services/services/ShipmentsService.js
- csc-services/services/constants/commons.js
- csc-services/services/constants/shipment.js
- csc-site-ssapp/code/pages/dashboard.html
- csc-site-ssapp/code/pages/notifications.html
- csc-site-ssapp/code/scripts/app-config.js
- csc-site-ssapp/code/templates/shipment/dashboard-shipment.html
- csc-site-ssapp/code/templates/shipment/tab-navigator.html
- csc-site-ssapp/code/templates/shipment/table-template-shipment.html
- csc-sponsor-ssapp/code/pages/dashboard.html
- csc-sponsor-ssapp/code/pages/notifications.html
- csc-sponsor-ssapp/code/scripts/app-config.js
- csc-sponsor-ssapp/code/templates/shipment/dashboard-shipment.html
- csc-sponsor-ssapp/code/templates/shipment/tab-navigator.html
- csc-sponsor-ssapp/code/templates/shipment/table-template-shipment.html
Displayed the proper Shipment ID on Notifications page
#123 SITE Shipments Dashboard page implementation
#124 Sponsor Shipments Dashboard page implementation
> Bug fixes, #123, #124

- csc-sponsor-ssapp/code/pages/shipment.html
- csc-sponsor-ssapp/code/webcardinal.json
I have created a shipment.html page for Sponsor to view the shipment details.
> PR for issue #165

- csc-services/controllers/impl/DashboardControllerImpl.js
- csc-services/controllers/impl/NotificationsControllerImpl.js
- csc-services/controllers/impl/SingleOrderControllerImpl.js
- csc-services/services/OrdersService.js
- csc-services/services/ShipmentsService.js
- csc-services/services/constants/index.js
- csc-services/services/constants/order.js
#193 Fixed View Shipment button for SITE and SPONSOR
#194 Removed the inheritance of the shipment into order
> #193 and #194

- csc-services/services/utilities/order/orderViewModel.js
- csc-sponsor-ssapp/code/pages/newOrder.html
- csc-sponsor-ssapp/code/scripts/controllers/NewOrderController.js
Made changes to make sure that Min Temperature is always <=Max Temperature while the inputs change. Please refer below snapshot
> #182 - Temperature Validation

- csc-services/controllers/impl/DashboardControllerImpl.js
- csc-services/controllers/impl/OrdersControllerImpl.js
- csc-services/controllers/impl/SingleShipmentControllerImpl.js
- csc-services/services/ShipmentsService.js
- csc-services/services/lib/DSUService.js
CMO: Notify Sponsor and Courier when a shipment is Ready for Dispatch
> #67 and #68

- csc-services/services/lib/NotificationService.js
Notifications sorting order changed to date from pk. Below is snapshot
> #195-finished

- csc-sponsor-ssapp/code/scripts/controllers/NewOrderController.js
Submit button is disabled on duplicated orders multiple submission, Below is snapshot
> #199 - Duplicated orders on multiple submission rectification

- csc-cmo-ssapp/code/modals/editShipment.html
- csc-services/services/constants/shipment.js
- csc-services/services/utilities/shipment/shipmentViewModel.js
- csc-sponsor-ssapp/code/scripts/controllers/NewOrderController.js
Shipper ID changed to dropdown.
> #220 Finished

- csc-cmo-ssapp/code/modals/scanShipmentModal.html
- csc-cmo-ssapp/code/pages/shipment.html
- csc-cmo-ssapp/code/scripts/controllers/ScanShipmentModalController.js
- csc-cmo-ssapp/code/templates/order/kit-summary.html
- csc-cmo-ssapp/code/templates/shipment/shipment-scan-summary.html
- csc-services/controllers/impl/SingleShipmentControllerImpl.js
@Mastaleru , @paiusCatalin - This PR is for - https://github.com/PharmaLedger-IMI/csc-workspace-main/issues/61
Few known issues in this PR:
1. CSS will need more improvements
2. data-if tag is somehow not working to display "No Kits Scanned" text on shipments page. `actions.showDefaultKitsAccordianText` was added to tackle this issue but it didn't help.
As discussed earlier in the calls, I have added just a boolean flag to shipment dsu to track scan completion.
> This PR fixes #61

- csc-services/controllers/impl/HistoryModalControllerImpl.js
I have modified the historymodalControllerImpl.js file to modify the history modal for Courier.
> PR for issue #249

- csc-services/controllers/impl/SingleOrderControllerImpl.js
Kindly review the changes and let me know for any concern.
> PR for issue #269

- csc-courier-ssapp/code/templates/dashboard-menu.html
I have changed the shipment icon for Courier dashboard.
> PR for issue #272

- csc-services/controllers/impl/SingleShipmentControllerImpl.js
> PR for issue #270

- csc-services/controllers/impl/DashboardControllerImpl.js
- csc-services/controllers/impl/helpers/ViewShipmentBaseController.js
- csc-site-ssapp/code/pages/dashboard.html
- csc-site-ssapp/code/pages/shipment.html
- csc-site-ssapp/code/templates/shipment/kit-summary.html
- csc-site-ssapp/code/templates/shipment/shipment-details.html
- csc-site-ssapp/code/templates/shipment/tab-navigator.html
- csc-sponsor-ssapp/code/templates/shipment/shipment-details.html
#225 - [SITE] : Update View Shipment page after the shipment has the status In Transit
#226 - [SPONSOR] : Update View Shipment page with the new information after the shipment has the status In Transit
#273 - [SITE]: Site should not see Orders on the Dashboard
> #225 #226 #273

- csc-services/controllers/impl/SingleShipmentControllerImpl.js
- csc-services/controllers/impl/helpers/ViewShipmentBaseController.js
Implemented refresh data modal when shipment is updated
> #267 finished

- csc-courier-ssapp/code/pages/shipment.html
- csc-courier-ssapp/code/scripts/controllers/CourierSingleShipmentController.js
> PR for issue #306

- csc-services/controllers/impl/SingleOrderControllerImpl.js
SPO the order single view is updated when shipment changes status from In Preparation to Ready for dispatch
> #326 finished

- csc-courier-ssapp/code/scripts/controllers/CourierSingleShipmentController.js
- csc-services/controllers/impl/SingleOrderControllerImpl.js
- csc-services/controllers/impl/SingleShipmentControllerImpl.js
[All Actors] Do not show multiple update modals for each edit is performed on the View single Shipment, View Single Order implemented.
> #328 finished

- csc-courier-ssapp/code/scripts/controllers/CourierSingleShipmentController.js
- csc-services/controllers/impl/SingleOrderControllerImpl.js
- csc-services/controllers/impl/SingleShipmentControllerImpl.js
Changes done to show only Update View button for all actors
> #336 finished

- csc-site-ssapp/code/pages/scan-shipment.html
- csc-site-ssapp/code/pages/shipment.html
- csc-site-ssapp/code/scripts/app-config.js
- csc-site-ssapp/code/scripts/controllers/ScanShipmentController.js
- csc-site-ssapp/code/scripts/controllers/SiteSingleShipmentController.js
- csc-site-ssapp/code/webcardinal.json
> PR for issue #230(shipment scan for SITE)

- csc-courier-ssapp/code/pages/deliver-shipment.html
- csc-courier-ssapp/code/scripts/controllers/DeliverShipmentController.js
> #317 Populated Shipment Data

- csc-courier-ssapp/code/scripts/controllers/CourierSingleShipmentController.js
- csc-courier-ssapp/code/scripts/controllers/ScanShipmentModalController.js
- csc-services/controllers/impl/DashboardControllerImpl.js
- csc-services/controllers/impl/SingleOrderControllerImpl.js
- csc-services/controllers/impl/SingleShipmentControllerImpl.js
Rectification done for the update view modal is shown on wrong order/shipment for all Actors
> #337 finished

- csc-courier-ssapp/code/modals/scanShipmentModal.html
- csc-courier-ssapp/code/scripts/controllers/DeliverShipmentController.js
- csc-courier-ssapp/code/scripts/controllers/ScanShipmentModalController.js
> PR for issue #327

- csc-courier-ssapp/code/pages/deliver-shipment.html
- csc-courier-ssapp/code/scripts/controllers/DeliverShipmentController.js
- csc-services/services/utilities/shipment/shipmentViewModel.js
In Deliver Shipment Controller  viewModelResolver is used in order to get the shipment form view-model for the form model.
> #317 Changed to viewModelResolver

- csc-courier-ssapp/code/pages/scan-shipment.html
- csc-courier-ssapp/code/pages/shipment.html
- csc-courier-ssapp/code/scripts/controllers/CourierSingleShipmentController.js
- csc-courier-ssapp/code/templates/shipment/shipment-order-details.html
> #390 finished

- csc-site-ssapp/code/pages/shipment.html
- csc-site-ssapp/code/templates/shipment/shipment-details.html
> #400 finished

- csc-services/controllers/impl/HistoryModalControllerImpl.js
- csc-site-ssapp/code/modals/historyModal.html
> Fixed all issues for #512 also fixed the empty history connector elements

- csc-cmo-ssapp/code/pages/edit-shipment.html
- csc-cmo-ssapp/code/scripts/controllers/EditShipmentController.js
> #469 - Shipment Details Mandatory fields added
